version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/frontend/node_modules
    environment:
      PORT: 3000
      ESLINT_NO_DEV_ERRORS: "true"
    stdin_open: true
    tty: true
    networks:
      - mynetwork
  backend:
    build: ./backend
    container_name: backend_container
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5001 -b '0.0.0.0'"
    ports:
      - 5001:5001
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - mailhog
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
      BACKEND_DATABASE_PASSWORD: prodpassword
    # dont terminate docker after running bin/dev
    tty: true
    networks:
      - mynetwork
  db:
    image: mysql:8.2.0
    container_name: db_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - mynetwork
  mailhog:
    container_name: mailhog_container
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    networks:
      - mynetwork
  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: strapidb
      DATABASE_PORT: 3306
      DATABASE_NAME: strapidb
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: HGw+TikDVKcwLBV++7BDwQ==
      APP_KEYS: 32PODKBW2ZqUM4ZbAyrQZQ==,SbLNWa8h0oNVYiNopqm9Hw==,kB/A73IN8tpak1scrCzVZg==,kGWAHpm9y2pHEiCjVVXX8w==
      NODE_ENV: development
    volumes:
      - ./cms/config:/opt/app/config
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/package.json
      - ./cms/yarn.lock:/opt/yarn.lock
      - ./cms/.env:/opt/app/.env
      - ./cms/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - mynetwork
    depends_on:
      - strapidb
  strapidb:
    container_name: strapidb
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: strapidb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - strapi-data:/var/lib/mysql
      #- ./data:/var/lib/mysql # if you want to use a bind folder
    ports:
      - "3310:3306"
    networks:
      - mynetwork

volumes:
  node_modules:
  strapi-data:
networks:
  mynetwork:
    name: mynetwork
