version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - node_modules:/frontend/node_modules
    environment:
      PORT: 3000
      ESLINT_NO_DEV_ERRORS: "true"
    stdin_open: true
    tty: true

volumes:
  node_modules: