version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
      - node_modules:/frontend/node_modules
    environment:
      PORT: 3000
      ESLINT_NO_DEV_ERRORS: "true"
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    container_name: backend_container
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5001 -b '0.0.0.0'"
    ports:
      - 5001:5001
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - mailhog
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: app
      DB_PASSWORD: password
      DB_HOST: db
      BACKEND_DATABASE_PASSWORD: prodpassword
    # dont terminate docker after running bin/dev
    tty: true
    networks:
      - mynetwork
  db:
    image: mysql:8.2.0
    container_name: db_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  mailhog:
    container_name: mailhog_container
    image: mailhog/mailhog
    ports:
      - "8025:8025"
volumes:
  node_modules:
networks:
  mynetwork:
    name: mynetwork
