# SurveyQuestion.create!(question_text: "What is your email?", user_type:"provider");
SurveyQuestion.create!(question_text: "Could you please share how scholarships are awarded, starting from the initial idea to the final selection?", user_type:"provider");
SurveyQuestion.create!(question_text: "What are the challenges you encounter in the process of granting scholarship - from ideation to awarding?", user_type:"provider");
SurveyQuestion.create!(question_text: "What are the challenges you encounter in posting scholarship?", user_type:"provider");
SurveyQuestion.create!(question_text: "What challenges did you face while going through your posting process that you believe the app could address? Are you open to using digital ways in solving these challenges?", user_type:"provider");
SurveyQuestion.create!(question_text: "What suggestions do you have to lessen these pain points in the posting process?", user_type:"provider");
SurveyQuestion.create!(question_text: "Do you use any services to post scholarship details?", user_type:"provider");
SurveyQuestion.create!(question_text: "Could you please share the process you followed to post your scholarship?", user_type:"provider");
SurveyQuestion.create!(question_text: "What's the motivation in providing scholarships?", user_type:"provider");
SurveyQuestion.create!(question_text: "Do you think you will benefit from this scholarship pooling app?", user_type:"provider");
SurveyQuestion.create!(question_text: "How probable is it that you would utilize the upcoming application management feature? On a scale of 1 (unlikely) to 5 (very likely), please rate your inclination to use the app, where students can browse, choose, and submit scholarship applications, and providers can oversee the application process.", user_type:"provider");
